// SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type GrantInitParameters struct {

	// (String) The name of the database on which to grant privileges.
	// The name of the database on which to grant privileges.
	DatabaseName *string `json:"databaseName,omitempty" tf:"database_name,omitempty"`

	// (Boolean) When this is set to true, multiple grants of the same type can be created.
	// When this is set to true, multiple grants of the same type can be created.
	EnableMultipleGrants *bool `json:"enableMultipleGrants,omitempty" tf:"enable_multiple_grants,omitempty"`

	// (String) The privilege to grant on the database. To grant all privileges, use the value ALL PRIVILEGES.
	// The privilege to grant on the database. To grant all privileges, use the value `ALL PRIVILEGES`.
	Privilege *string `json:"privilege,omitempty" tf:"privilege,omitempty"`

	// (String) The name of the role to revert ownership to on destroy. Has no effect unless privilege is set to OWNERSHIP
	// The name of the role to revert ownership to on destroy. Has no effect unless `privilege` is set to `OWNERSHIP`
	RevertOwnershipToRoleName *string `json:"revertOwnershipToRoleName,omitempty" tf:"revert_ownership_to_role_name,omitempty"`

	// (Set of String) Grants privilege to these roles.
	// Grants privilege to these roles.
	Roles []*string `json:"roles,omitempty" tf:"roles,omitempty"`

	// (Set of String) Grants privilege to these shares.
	// Grants privilege to these shares.
	Shares []*string `json:"shares,omitempty" tf:"shares,omitempty"`

	// (Boolean) When this is set to true, allows the recipient role to grant the privileges to other roles.
	// When this is set to true, allows the recipient role to grant the privileges to other roles.
	WithGrantOption *bool `json:"withGrantOption,omitempty" tf:"with_grant_option,omitempty"`
}

type GrantObservation struct {

	// (String) The name of the database on which to grant privileges.
	// The name of the database on which to grant privileges.
	DatabaseName *string `json:"databaseName,omitempty" tf:"database_name,omitempty"`

	// (Boolean) When this is set to true, multiple grants of the same type can be created.
	// When this is set to true, multiple grants of the same type can be created.
	EnableMultipleGrants *bool `json:"enableMultipleGrants,omitempty" tf:"enable_multiple_grants,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The privilege to grant on the database. To grant all privileges, use the value ALL PRIVILEGES.
	// The privilege to grant on the database. To grant all privileges, use the value `ALL PRIVILEGES`.
	Privilege *string `json:"privilege,omitempty" tf:"privilege,omitempty"`

	// (String) The name of the role to revert ownership to on destroy. Has no effect unless privilege is set to OWNERSHIP
	// The name of the role to revert ownership to on destroy. Has no effect unless `privilege` is set to `OWNERSHIP`
	RevertOwnershipToRoleName *string `json:"revertOwnershipToRoleName,omitempty" tf:"revert_ownership_to_role_name,omitempty"`

	// (Set of String) Grants privilege to these roles.
	// Grants privilege to these roles.
	Roles []*string `json:"roles,omitempty" tf:"roles,omitempty"`

	// (Set of String) Grants privilege to these shares.
	// Grants privilege to these shares.
	Shares []*string `json:"shares,omitempty" tf:"shares,omitempty"`

	// (Boolean) When this is set to true, allows the recipient role to grant the privileges to other roles.
	// When this is set to true, allows the recipient role to grant the privileges to other roles.
	WithGrantOption *bool `json:"withGrantOption,omitempty" tf:"with_grant_option,omitempty"`
}

type GrantParameters struct {

	// (String) The name of the database on which to grant privileges.
	// The name of the database on which to grant privileges.
	// +kubebuilder:validation:Optional
	DatabaseName *string `json:"databaseName,omitempty" tf:"database_name,omitempty"`

	// (Boolean) When this is set to true, multiple grants of the same type can be created.
	// When this is set to true, multiple grants of the same type can be created.
	// +kubebuilder:validation:Optional
	EnableMultipleGrants *bool `json:"enableMultipleGrants,omitempty" tf:"enable_multiple_grants,omitempty"`

	// (String) The privilege to grant on the database. To grant all privileges, use the value ALL PRIVILEGES.
	// The privilege to grant on the database. To grant all privileges, use the value `ALL PRIVILEGES`.
	// +kubebuilder:validation:Optional
	Privilege *string `json:"privilege,omitempty" tf:"privilege,omitempty"`

	// (String) The name of the role to revert ownership to on destroy. Has no effect unless privilege is set to OWNERSHIP
	// The name of the role to revert ownership to on destroy. Has no effect unless `privilege` is set to `OWNERSHIP`
	// +kubebuilder:validation:Optional
	RevertOwnershipToRoleName *string `json:"revertOwnershipToRoleName,omitempty" tf:"revert_ownership_to_role_name,omitempty"`

	// (Set of String) Grants privilege to these roles.
	// Grants privilege to these roles.
	// +kubebuilder:validation:Optional
	Roles []*string `json:"roles,omitempty" tf:"roles,omitempty"`

	// (Set of String) Grants privilege to these shares.
	// Grants privilege to these shares.
	// +kubebuilder:validation:Optional
	Shares []*string `json:"shares,omitempty" tf:"shares,omitempty"`

	// (Boolean) When this is set to true, allows the recipient role to grant the privileges to other roles.
	// When this is set to true, allows the recipient role to grant the privileges to other roles.
	// +kubebuilder:validation:Optional
	WithGrantOption *bool `json:"withGrantOption,omitempty" tf:"with_grant_option,omitempty"`
}

// GrantSpec defines the desired state of Grant
type GrantSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     GrantParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider GrantInitParameters `json:"initProvider,omitempty"`
}

// GrantStatus defines the observed state of Grant.
type GrantStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        GrantObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// Grant is the Schema for the Grants API.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,snowflake}
type Grant struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.databaseName) || (has(self.initProvider) && has(self.initProvider.databaseName))",message="spec.forProvider.databaseName is a required parameter"
	Spec   GrantSpec   `json:"spec"`
	Status GrantStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// GrantList contains a list of Grants
type GrantList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Grant `json:"items"`
}

// Repository type metadata.
var (
	Grant_Kind             = "Grant"
	Grant_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Grant_Kind}.String()
	Grant_KindAPIVersion   = Grant_Kind + "." + CRDGroupVersion.String()
	Grant_GroupVersionKind = CRDGroupVersion.WithKind(Grant_Kind)
)

func init() {
	SchemeBuilder.Register(&Grant{}, &GrantList{})
}
