apiVersion: snowflake.snowflake.crossplane.io/v1alpha1
kind: Database
metadata:
  annotations:
    meta.upbound.io/example-id: snowflake/v1alpha1/database
  labels:
    testing.upbound.io/example-name: simple
  name: simple
spec:
  forProvider:
    comment: test comment
    dataRetentionTimeInDays: 3
