//go:build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseGrant) DeepCopyInto(out *DatabaseGrant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseGrant.
func (in *DatabaseGrant) DeepCopy() *DatabaseGrant {
	if in == nil {
		return nil
	}
	out := new(DatabaseGrant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatabaseGrant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseGrantInitParameters) DeepCopyInto(out *DatabaseGrantInitParameters) {
	*out = *in
	if in.EnableMultipleGrants != nil {
		in, out := &in.EnableMultipleGrants, &out.EnableMultipleGrants
		*out = new(bool)
		**out = **in
	}
	if in.Privilege != nil {
		in, out := &in.Privilege, &out.Privilege
		*out = new(string)
		**out = **in
	}
	if in.RevertOwnershipToRoleName != nil {
		in, out := &in.RevertOwnershipToRoleName, &out.RevertOwnershipToRoleName
		*out = new(string)
		**out = **in
	}
	if in.WithGrantOption != nil {
		in, out := &in.WithGrantOption, &out.WithGrantOption
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseGrantInitParameters.
func (in *DatabaseGrantInitParameters) DeepCopy() *DatabaseGrantInitParameters {
	if in == nil {
		return nil
	}
	out := new(DatabaseGrantInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseGrantList) DeepCopyInto(out *DatabaseGrantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DatabaseGrant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseGrantList.
func (in *DatabaseGrantList) DeepCopy() *DatabaseGrantList {
	if in == nil {
		return nil
	}
	out := new(DatabaseGrantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatabaseGrantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseGrantObservation) DeepCopyInto(out *DatabaseGrantObservation) {
	*out = *in
	if in.DatabaseName != nil {
		in, out := &in.DatabaseName, &out.DatabaseName
		*out = new(string)
		**out = **in
	}
	if in.EnableMultipleGrants != nil {
		in, out := &in.EnableMultipleGrants, &out.EnableMultipleGrants
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Privilege != nil {
		in, out := &in.Privilege, &out.Privilege
		*out = new(string)
		**out = **in
	}
	if in.RevertOwnershipToRoleName != nil {
		in, out := &in.RevertOwnershipToRoleName, &out.RevertOwnershipToRoleName
		*out = new(string)
		**out = **in
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Shares != nil {
		in, out := &in.Shares, &out.Shares
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.WithGrantOption != nil {
		in, out := &in.WithGrantOption, &out.WithGrantOption
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseGrantObservation.
func (in *DatabaseGrantObservation) DeepCopy() *DatabaseGrantObservation {
	if in == nil {
		return nil
	}
	out := new(DatabaseGrantObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseGrantParameters) DeepCopyInto(out *DatabaseGrantParameters) {
	*out = *in
	if in.DatabaseName != nil {
		in, out := &in.DatabaseName, &out.DatabaseName
		*out = new(string)
		**out = **in
	}
	if in.DatabaseRef != nil {
		in, out := &in.DatabaseRef, &out.DatabaseRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.DatabaseSelector != nil {
		in, out := &in.DatabaseSelector, &out.DatabaseSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.EnableMultipleGrants != nil {
		in, out := &in.EnableMultipleGrants, &out.EnableMultipleGrants
		*out = new(bool)
		**out = **in
	}
	if in.Privilege != nil {
		in, out := &in.Privilege, &out.Privilege
		*out = new(string)
		**out = **in
	}
	if in.RevertOwnershipToRoleName != nil {
		in, out := &in.RevertOwnershipToRoleName, &out.RevertOwnershipToRoleName
		*out = new(string)
		**out = **in
	}
	if in.RoleRefs != nil {
		in, out := &in.RoleRefs, &out.RoleRefs
		*out = make([]v1.Reference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RoleSelector != nil {
		in, out := &in.RoleSelector, &out.RoleSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ShareRefs != nil {
		in, out := &in.ShareRefs, &out.ShareRefs
		*out = make([]v1.Reference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ShareSelector != nil {
		in, out := &in.ShareSelector, &out.ShareSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Shares != nil {
		in, out := &in.Shares, &out.Shares
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.WithGrantOption != nil {
		in, out := &in.WithGrantOption, &out.WithGrantOption
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseGrantParameters.
func (in *DatabaseGrantParameters) DeepCopy() *DatabaseGrantParameters {
	if in == nil {
		return nil
	}
	out := new(DatabaseGrantParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseGrantSpec) DeepCopyInto(out *DatabaseGrantSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseGrantSpec.
func (in *DatabaseGrantSpec) DeepCopy() *DatabaseGrantSpec {
	if in == nil {
		return nil
	}
	out := new(DatabaseGrantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseGrantStatus) DeepCopyInto(out *DatabaseGrantStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseGrantStatus.
func (in *DatabaseGrantStatus) DeepCopy() *DatabaseGrantStatus {
	if in == nil {
		return nil
	}
	out := new(DatabaseGrantStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleGrant) DeepCopyInto(out *RoleGrant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleGrant.
func (in *RoleGrant) DeepCopy() *RoleGrant {
	if in == nil {
		return nil
	}
	out := new(RoleGrant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RoleGrant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleGrantInitParameters) DeepCopyInto(out *RoleGrantInitParameters) {
	*out = *in
	if in.EnableMultipleGrants != nil {
		in, out := &in.EnableMultipleGrants, &out.EnableMultipleGrants
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleGrantInitParameters.
func (in *RoleGrantInitParameters) DeepCopy() *RoleGrantInitParameters {
	if in == nil {
		return nil
	}
	out := new(RoleGrantInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleGrantList) DeepCopyInto(out *RoleGrantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RoleGrant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleGrantList.
func (in *RoleGrantList) DeepCopy() *RoleGrantList {
	if in == nil {
		return nil
	}
	out := new(RoleGrantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RoleGrantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleGrantObservation) DeepCopyInto(out *RoleGrantObservation) {
	*out = *in
	if in.EnableMultipleGrants != nil {
		in, out := &in.EnableMultipleGrants, &out.EnableMultipleGrants
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.RoleName != nil {
		in, out := &in.RoleName, &out.RoleName
		*out = new(string)
		**out = **in
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleGrantObservation.
func (in *RoleGrantObservation) DeepCopy() *RoleGrantObservation {
	if in == nil {
		return nil
	}
	out := new(RoleGrantObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleGrantParameters) DeepCopyInto(out *RoleGrantParameters) {
	*out = *in
	if in.EnableMultipleGrants != nil {
		in, out := &in.EnableMultipleGrants, &out.EnableMultipleGrants
		*out = new(bool)
		**out = **in
	}
	if in.MemberRoleRefs != nil {
		in, out := &in.MemberRoleRefs, &out.MemberRoleRefs
		*out = make([]v1.Reference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MemberRoleSelector != nil {
		in, out := &in.MemberRoleSelector, &out.MemberRoleSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.MemberUserRefs != nil {
		in, out := &in.MemberUserRefs, &out.MemberUserRefs
		*out = make([]v1.Reference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MemberUserSelector != nil {
		in, out := &in.MemberUserSelector, &out.MemberUserSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.RoleName != nil {
		in, out := &in.RoleName, &out.RoleName
		*out = new(string)
		**out = **in
	}
	if in.RoleRef != nil {
		in, out := &in.RoleRef, &out.RoleRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.RoleSelector != nil {
		in, out := &in.RoleSelector, &out.RoleSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleGrantParameters.
func (in *RoleGrantParameters) DeepCopy() *RoleGrantParameters {
	if in == nil {
		return nil
	}
	out := new(RoleGrantParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleGrantSpec) DeepCopyInto(out *RoleGrantSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleGrantSpec.
func (in *RoleGrantSpec) DeepCopy() *RoleGrantSpec {
	if in == nil {
		return nil
	}
	out := new(RoleGrantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleGrantStatus) DeepCopyInto(out *RoleGrantStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleGrantStatus.
func (in *RoleGrantStatus) DeepCopy() *RoleGrantStatus {
	if in == nil {
		return nil
	}
	out := new(RoleGrantStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchemaGrant) DeepCopyInto(out *SchemaGrant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchemaGrant.
func (in *SchemaGrant) DeepCopy() *SchemaGrant {
	if in == nil {
		return nil
	}
	out := new(SchemaGrant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SchemaGrant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchemaGrantInitParameters) DeepCopyInto(out *SchemaGrantInitParameters) {
	*out = *in
	if in.EnableMultipleGrants != nil {
		in, out := &in.EnableMultipleGrants, &out.EnableMultipleGrants
		*out = new(bool)
		**out = **in
	}
	if in.OnAll != nil {
		in, out := &in.OnAll, &out.OnAll
		*out = new(bool)
		**out = **in
	}
	if in.OnFuture != nil {
		in, out := &in.OnFuture, &out.OnFuture
		*out = new(bool)
		**out = **in
	}
	if in.Privilege != nil {
		in, out := &in.Privilege, &out.Privilege
		*out = new(string)
		**out = **in
	}
	if in.RevertOwnershipToRoleName != nil {
		in, out := &in.RevertOwnershipToRoleName, &out.RevertOwnershipToRoleName
		*out = new(string)
		**out = **in
	}
	if in.WithGrantOption != nil {
		in, out := &in.WithGrantOption, &out.WithGrantOption
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchemaGrantInitParameters.
func (in *SchemaGrantInitParameters) DeepCopy() *SchemaGrantInitParameters {
	if in == nil {
		return nil
	}
	out := new(SchemaGrantInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchemaGrantList) DeepCopyInto(out *SchemaGrantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SchemaGrant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchemaGrantList.
func (in *SchemaGrantList) DeepCopy() *SchemaGrantList {
	if in == nil {
		return nil
	}
	out := new(SchemaGrantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SchemaGrantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchemaGrantObservation) DeepCopyInto(out *SchemaGrantObservation) {
	*out = *in
	if in.DatabaseName != nil {
		in, out := &in.DatabaseName, &out.DatabaseName
		*out = new(string)
		**out = **in
	}
	if in.EnableMultipleGrants != nil {
		in, out := &in.EnableMultipleGrants, &out.EnableMultipleGrants
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.OnAll != nil {
		in, out := &in.OnAll, &out.OnAll
		*out = new(bool)
		**out = **in
	}
	if in.OnFuture != nil {
		in, out := &in.OnFuture, &out.OnFuture
		*out = new(bool)
		**out = **in
	}
	if in.Privilege != nil {
		in, out := &in.Privilege, &out.Privilege
		*out = new(string)
		**out = **in
	}
	if in.RevertOwnershipToRoleName != nil {
		in, out := &in.RevertOwnershipToRoleName, &out.RevertOwnershipToRoleName
		*out = new(string)
		**out = **in
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SchemaName != nil {
		in, out := &in.SchemaName, &out.SchemaName
		*out = new(string)
		**out = **in
	}
	if in.Shares != nil {
		in, out := &in.Shares, &out.Shares
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.WithGrantOption != nil {
		in, out := &in.WithGrantOption, &out.WithGrantOption
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchemaGrantObservation.
func (in *SchemaGrantObservation) DeepCopy() *SchemaGrantObservation {
	if in == nil {
		return nil
	}
	out := new(SchemaGrantObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchemaGrantParameters) DeepCopyInto(out *SchemaGrantParameters) {
	*out = *in
	if in.DatabaseName != nil {
		in, out := &in.DatabaseName, &out.DatabaseName
		*out = new(string)
		**out = **in
	}
	if in.DatabaseRef != nil {
		in, out := &in.DatabaseRef, &out.DatabaseRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.DatabaseSelector != nil {
		in, out := &in.DatabaseSelector, &out.DatabaseSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.EnableMultipleGrants != nil {
		in, out := &in.EnableMultipleGrants, &out.EnableMultipleGrants
		*out = new(bool)
		**out = **in
	}
	if in.OnAll != nil {
		in, out := &in.OnAll, &out.OnAll
		*out = new(bool)
		**out = **in
	}
	if in.OnFuture != nil {
		in, out := &in.OnFuture, &out.OnFuture
		*out = new(bool)
		**out = **in
	}
	if in.Privilege != nil {
		in, out := &in.Privilege, &out.Privilege
		*out = new(string)
		**out = **in
	}
	if in.RevertOwnershipToRoleName != nil {
		in, out := &in.RevertOwnershipToRoleName, &out.RevertOwnershipToRoleName
		*out = new(string)
		**out = **in
	}
	if in.RoleRefs != nil {
		in, out := &in.RoleRefs, &out.RoleRefs
		*out = make([]v1.Reference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RoleSelector != nil {
		in, out := &in.RoleSelector, &out.RoleSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SchemaName != nil {
		in, out := &in.SchemaName, &out.SchemaName
		*out = new(string)
		**out = **in
	}
	if in.SchemaRef != nil {
		in, out := &in.SchemaRef, &out.SchemaRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.SchemaSelector != nil {
		in, out := &in.SchemaSelector, &out.SchemaSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.ShareRefs != nil {
		in, out := &in.ShareRefs, &out.ShareRefs
		*out = make([]v1.Reference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ShareSelector != nil {
		in, out := &in.ShareSelector, &out.ShareSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Shares != nil {
		in, out := &in.Shares, &out.Shares
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.WithGrantOption != nil {
		in, out := &in.WithGrantOption, &out.WithGrantOption
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchemaGrantParameters.
func (in *SchemaGrantParameters) DeepCopy() *SchemaGrantParameters {
	if in == nil {
		return nil
	}
	out := new(SchemaGrantParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchemaGrantSpec) DeepCopyInto(out *SchemaGrantSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchemaGrantSpec.
func (in *SchemaGrantSpec) DeepCopy() *SchemaGrantSpec {
	if in == nil {
		return nil
	}
	out := new(SchemaGrantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchemaGrantStatus) DeepCopyInto(out *SchemaGrantStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchemaGrantStatus.
func (in *SchemaGrantStatus) DeepCopy() *SchemaGrantStatus {
	if in == nil {
		return nil
	}
	out := new(SchemaGrantStatus)
	in.DeepCopyInto(out)
	return out
}
