apiVersion: database.crossplane.io/v1alpha1
kind: Grant
metadata:
  annotations:
    meta.upbound.io/example-id: database/v1alpha1/grant
  labels:
    testing.upbound.io/example-name: grant
  name: grant
spec:
  forProvider:
    databaseSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    privilege: USAGE
    roleRefs:
    - name: example
    - name: example
    shareRefs:
    - name: example
    - name: example
    withGrantOption: false
