apiVersion: grant.snowflake.crossplane.io/v1alpha1
kind: RoleGrant
metadata:
  annotations:
    meta.upbound.io/example-id: grant/v1alpha1/rolegrant
  labels:
    testing.upbound.io/example-name: grants
  name: grants
spec:
  forProvider:
    memberRoleRefs:
    - name: other_role
    memberUserRefs:
    - name: user
    - name: user2
    roleSelector:
      matchLabels:
        testing.upbound.io/example-name: role

---

apiVersion: snowflake.snowflake.crossplane.io/v1alpha1
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: grant/v1alpha1/rolegrant
  labels:
    testing.upbound.io/example-name: other_role
  name: other-role
spec:
  forProvider: {}

---

apiVersion: snowflake.snowflake.crossplane.io/v1alpha1
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: grant/v1alpha1/rolegrant
  labels:
    testing.upbound.io/example-name: role
  name: role
spec:
  forProvider:
    comment: for testing

---

apiVersion: snowflake.snowflake.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: grant/v1alpha1/rolegrant
  labels:
    testing.upbound.io/example-name: user
  name: user
spec:
  forProvider:
    comment: for testing

---

apiVersion: snowflake.snowflake.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: grant/v1alpha1/rolegrant
  labels:
    testing.upbound.io/example-name: user2
  name: user2
spec:
  forProvider:
    comment: for testing
